name: Merge QA to Main and Deploy to Production

on:
  push:
    branches:
      - qa  # Este flujo de trabajo se ejecuta cuando hay un cambio en la rama 'qa'

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Actualización a la versión v3

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Checkout main branch
        run: git checkout main

      - name: Pull latest main changes
        run: git pull origin main  # Asegúrate de que main esté actualizado antes del merge

      - name: Merge qa into main
        run: |
          git merge qa --no-ff -m "Merge qa into main"  # Asegura un merge explícito
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Necesario para hacer push al repositorio

  deploy:
    runs-on: ubuntu-latest
    needs: merge  # El trabajo de despliegue depende de que el merge sea exitoso

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Actualización a la versión v3

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          helm-version: '3.x'  # Especifica la versión de Helm

      - name: Set up Kubernetes
        uses: azure/setup-kubernetes@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}  # Usa tu kubeconfig guardado en GitHub Secrets

      - name: Deploy with Helm
        run: |
          helm upgrade --install periplay-backend ./helm-chart-backend-prod --namespace prod-periplay --values ./values-prod.yaml
